### PR TITLE
MTKA-1907: Fix missing menus when using Twenty Twenty-Three default theme

### PR DESCRIPTION
**Pull request by nickcernis**
Adjusts the `acm.json` export file and docs to export the `current_theme`, `stylesheet` and `template`.

Without this, the theme mods for Twenty Twenty-Two do not apply if a new site is using Twenty Twenty-Three, so menus are not assigned to the expected locations.

```json
    "wp-options": {
        "category_base": "category",
        "permalink_structure": "\/posts\/%postname%\/",
        "nav_menu_options": {
            "0": false,
            "auto_add": []
        },
        "theme_mods_twentytwentytwo": {
            "nav_menu_locations": {
                "primary": 2,
                "footer": 3
            },
            "custom_css_post_id": -1
        },
        "current_theme": "Twenty Twenty-Two",
        "stylesheet": "twentytwentytwo",
        "template": "twentytwentytwo"
    }
```

On merging this to main, I recommend testing with a fresh site on Atlas infrastructure to confirm menus are working there again.

### Jira
- [MTKA-1907](https://wpengine.atlassian.net/browse/MTKA-1907)

### To test
- Create a fresh site in Local.
- Install ACM and Faust: `wp plugin install --activate atlas-content-modeler faustwp`.
- Import the blueprint file from this branch: `wp acm blueprint import https://github.com/wpengine/atlas-blueprint-portfolio/raw/nc/fix-menus-twenty-twenty-three/acm-blueprint.zip`
- Confirm the menu locations are set correctly at Appearance → Menus:

Screenshot 2023-01-17 at 19 03 56

[MTKA-1907]: https://wpengine.atlassian.net/browse/MTKA-1907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mindctrl** [comment]
Thoughts on also defining the `current_theme` and `stylesheet` options so the theme mod settings always work as intended?

**Comment by nickcernis** [comment]
> Thoughts on also defining the current_theme and stylesheet options so the theme mod settings always work as intended?

@mindctrl I thought about that, but wasn't sure what the impact would be if the site doesn't have that theme for some reason. (Say, if `current_theme` was removed when the new one rolls in.) If you think that risk is low then I'm happy to make that change here.

**Comment by anthonyburchell** [comment]
I think hard defining twentytwentytwo is our safest bet considering FSE things that could get in the way over time. Also considering these are headless sites so it makes sense that FSE might not be the first pick when setting up a site.

**Comment by mindctrl** [comment]
@nickcernis good thoughts. I think the risk is low, and it's probably more likely we'll encounter this issue in the future when a new default theme lands if we don't add it. It would also be nice for the manifests to be deterministic, to the extent it makes sense.

**Comment by mindctrl** [comment]
I don't have a strong opinion on 2022 vs 2023 theme, but someone from @wpengine/merlin might.

**Comment by josephfusco** [comment]
@nickcernis Confirming that your solution is working with a fresh site!

@mindctrl @anthonyburchell I agree that FSE could pose some challenges down the road. I can say that we have already needed to [make some adjustments relating to FSE](https://github.com/wpengine/faustjs/pull/874). That said, this solution looks great. No strong opinions on which default theme should be in place.

@nickcernis The failing Format job on this PR was addressed in [another open PR](https://github.com/wpengine/atlas-blueprint-portfolio/pull/105), specifically [this commit](https://github.com/wpengine/atlas-blueprint-portfolio/pull/105/commits/1907b9345588de44560fb3c020cbfdf5fa72169f), that is currently blocked so feel free to include in this PR.

**Comment by nickcernis** [comment]
@anthonyburchell @josephfusco @mindctrl Thanks for your feedback!

This is ready for another look (same testing steps as before):

```
wp acm blueprint import https://github.com/wpengine/atlas-blueprint-portfolio/raw/nc/fix-menus-twenty-twenty-three/acm-blueprint.zip
```

I have:

- Reverted to Twenty Twenty-Two as the active theme.
- Exported `current_theme`, `stylesheet` and `template` options. (Without `template`, Twenty Twenty-Two fatal errors when Twenty Twenty-Three is active because it looks for includes in the `twentytwentythree` template path.)
- Updated docs to make it clear people should verify that `twentytwentytwo` is the active theme before exporting, and to suggest `wp acm reset --yes --all` as a way to remove the Hello World/Sample Page posts.
- Cherry picked the formatting commit so CI checks pass here.

All seems well but I have not tested this on Atlas infrastructure.

**Review by josephfusco — APPROVED** [review]
Awesome thank you @nickcernis 💯

**Pull request merged**
