### PR TITLE
Merl 711 update blueprints to use 2023 default theme

### PR DESCRIPTION
**Pull request by TeresaGobble**
[MERL-711](https://wpengine.atlassian.net/jira/software/c/projects/MERL/boards/1007?modal=detail&selectedIssue=MERL-711) changes the theme mods and current theme to 2023 in the acm.json file as an update for Atlas Portal.

**To test:** 
Clone this branch and deploy it in [Atlas Portal. ](https://my.wpengine.com/atlas#/)
Check the resulting layout on the resulting site to ensure the update does not introduce any layout shifts or breaks.

[MERL-711]: https://wpengine.atlassian.net/browse/MERL-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by TeresaGobble** [comment]
I have updated the acm-blueprint zipped document to include the suggestion by @mindctrl to ensure the `current_theme, stylesheet, template,` and `theme_mods` are all 2023. 

image


Thank you for talking with me John!

**Comment by mindctrl** [comment]
@TeresaGobble the json file looks correct, but I noticed there's no media folder within the zip to go with the media defined in the json file. Is that intentional?

**Comment by TeresaGobble** [comment]
> @TeresaGobble the json file looks correct, but I noticed there's no media folder within the zip to go with the media defined in the json file. Is that intentional?

Thank you for catching that John, I've just re-added the media folder. I appreciate it!

**Review by mindctrl — APPROVED** [review]
LGTM. Confirmed import works as expected in local dev site. I did not test in Atlas portal, as I wasn't sure of how to do that with this zip file.

**Review by josephfusco — APPROVED** [review]

**Pull request merged**
