### PR TITLE
Add popular themes nav mods to ACM Blueprint to hopefully asign menu upon creation

### PR DESCRIPTION
**Pull request by blakewilson**

### CODE REVIEW

**Comment by blakewilson** [comment]
Please view the `acm-blueprint.zip` diff here:
https://github.com/wpengine/atlas-blueprint-portfolio/runs/5837414755?check_suite_focus=true

**Review by apmatthews — CHANGES_REQUESTED** [review]
I agree this is the simplest solution until we have a more robust way of handing menus. We'll just need to add the other `theme_mods_` option names to the export command in `DEVELOPMENT.md` so we don't lose them on a later exports.

**Comment by blakewilson** [comment]
@apmatthews Ah true. I did not consider that. For whatever reason I thought this would merge in with future ACM exports. Maybe this isn't the right solution.

**Comment by apmatthews** [comment]
Yeah, on second thought, even if we were disciplined and exported all the right options, we'd still have to remember to change those option values manually if we updated location assignments 🤔.

**Comment by blakewilson** [comment]
Yeah, I don't think it's worth it. I'll close out this PR.

**Pull request closed without merging**
